/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animation;

import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * @author RealLife
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final int STEP = 3;
    private int kx = 1;
    private int ky = 1;
    private NewThread thread;
    private final Random random = new Random();
    private int score = 0;
    private MovedPanelListener movedPanelListener;


    public NewJFrame() {
        initComponents();
        jPanel2.setLayout(null);
        jBox.setLocation(random.nextInt(jPanel2.getWidth() - jBox.getWidth()), 10);
        movedPanelListener = new MovedPanelListener(this);
        movedPanel.addKeyListener(movedPanelListener);
        movedPanel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBox = new javax.swing.JPanel();
        movedPanel = new javax.swing.JPanel();
        jLabelScore = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Stop");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClickStop(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCancelClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Start");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnlickStart(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3)
                                        .addComponent(jButton4))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelDrag(evt);
            }
        });

        jBox.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jBoxLayout = new javax.swing.GroupLayout(jBox);
        jBox.setLayout(jBoxLayout);
        jBoxLayout.setHorizontalGroup(
                jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 19, Short.MAX_VALUE)
        );
        jBoxLayout.setVerticalGroup(
                jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 18, Short.MAX_VALUE)
        );

        movedPanel.setBackground(new java.awt.Color(0, 0, 0));
        movedPanel.setPreferredSize(new java.awt.Dimension(100, 15));
        movedPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movedPanelEvent(evt);
            }
        });
        movedPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                movedPanelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout movedPanelLayout = new javax.swing.GroupLayout(movedPanel);
        movedPanel.setLayout(movedPanelLayout);
        movedPanelLayout.setHorizontalGroup(
                movedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        movedPanelLayout.setVerticalGroup(
                movedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabelScore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScore.setText("0");
        jLabelScore.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(220, 220, 220))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(movedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(255, 255, 255))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 79, Short.MAX_VALUE)
                                                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelScore))
                                .addGap(129, 129, 129)
                                .addComponent(movedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelClicked
        this.dispose();
    }//GEN-LAST:event_jBtnCancelClicked

    private void jBtnlickStart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnlickStart
        thread = new NewThread(this, 20);
        thread.start();
        btnSwitch();
        movedPanel.requestFocusInWindow();
    }//GEN-LAST:event_jBtnlickStart

    private void jBtnClickStop(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClickStop
        thread.stop();
        btnSwitch();
    }//GEN-LAST:event_jBtnClickStop

    private void jPanelDrag(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDrag

    }//GEN-LAST:event_jPanelDrag

    private void movedPanelEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movedPanelEvent

        try {
            Point p = jPanel2.getMousePosition();
            p.y = movedPanel.getY();
            movedPanel.setLocation(p);
        } catch (NullPointerException ex) {

        }
    }//GEN-LAST:event_movedPanelEvent


    private void movedPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_movedPanelKeyPressed
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_movedPanelKeyPressed


    public void btnSwitch() {
        jButton4.setEnabled(!jButton4.isEnabled());
        jButton2.setEnabled(!jButton2.isEnabled());
    }

    public void moveBox() {
        Point p = jBox.getLocation();

        int coordXBox = p.x;
        int centerBox = p.x + jBox.getWidth() / 2;
        int rightSideBox = centerBox + jBox.getWidth() / 2;

        int coordXPan = movedPanel.getX();
        int borderXPan = movedPanel.getX() + movedPanel.getWidth();
        int coordYPan = movedPanel.getY();

        if (p.x >= jPanel2.getWidth() - jBox.getWidth() || (p.x <= 0))
            kx = -kx;
        if ((p.y <= 0))
            ky = -ky;


        if ((centerBox > coordXPan && rightSideBox < borderXPan && (p.y + jBox.getHeight() > coordYPan)) ||
                (coordXBox > coordXPan && centerBox < borderXPan && (p.y + jBox.getHeight() > coordYPan))) {

            if (p.y + jBox.getHeight() - coordYPan < 5) {

                score += 10;
                switch (score) {
                    case 20 -> thread.setDelay(15);
                    case 40 -> thread.setDelay(13);
                    case 60 -> thread.setDelay(11);
                    case 80 -> thread.setDelay(9);
                    case 100 -> thread.setDelay(50);
                    case 110 -> thread.setDelay(8);
                }

                String scoreStr = "" + score;
                jLabelScore.setText(scoreStr);
                ky = -ky;
            }
        }


        if (p.y >= jPanel2.getHeight()) {
            thread.canMove = false;
            this.dispose();
        }

        p.move(p.x + kx * STEP, p.y + ky * STEP);
        jBox.setLocation(p);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel movedPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getjBox() {
        return jBox;
    }

    public void setjBox(JPanel jBox) {
        this.jBox = jBox;
    }

    public void movedPanelOnKeyBoard() throws InterruptedException {
        Point p = movedPanel.getLocation();
        if (movedPanelListener.isLeft) {
            if (p.x >= 0) {
                p.x -= 20;
                movedPanel.setLocation(p);
                movedPanelListener.isLeft = false;
            }
        }
        if (movedPanelListener.isRight) {
            if (p.x <= jPanel2.getWidth() - movedPanel.getWidth()) {
                p.x += 20;
                movedPanel.setLocation(p);
                movedPanelListener.isRight = false;
            }
        }
    }

}
